
---
title: "04-PCA"
output:
  html_document:
    toc: true
---


# Principal component analysis (PCA)

```{r}
%md

Dimensionality reduction techniques are widely used and versatile techniques that can be used to:

find structure in features
pre-processing for other ML algorithms, and
aid in visualisation.
The basic principle of dimensionality reduction techniques is to transform the data into a new space that summarise properties of the whole data set along a reduced number of dimensions. These are then ideal candidates used to visualise the data along these reduced number of informative dimensions.
```


```{r}
%md
Principal Component Analysis (PCA) is a technique that transforms the original n-dimensional data into a new n-dimensional space.

These new dimensions are linear combinations of the original data, i.e. they are composed of proportions of the original variables.
Along these new dimensions, called principal components, the data expresses most of its variability along the first PC, then second, …
Principal components are orthogonal to each other, i.e. non-correlated.
Original data (left). PC1 will maximise the variability while minimising the residuals (centre). PC2 is orthogonal to PC1 (right).
Figure 4.8: Original data (left). PC1 will maximise the variability while minimising the residuals (centre). PC2 is orthogonal to PC1 (right).

In R, we can use the prcomp function.

Let’s explore PCA on the iris data. While it contains only 4 variables, is already becomes difficult to visualise the 3 groups along all these dimensions.
```


```{r}
%md
## In other words
#### 2 main goals of dimensionality reduciton
- find structure in features
- aid in visualization
#### PCA has 3 goals
- find a linear combintion of variables to create principle components
- maintain as much variance in the data as possible
- principal components are uncorrelated (i.e. orthogonoal to each other)
#### intuition
- with an x y correlation scatter plot, the best 1 dimension to explain the variance in the data is the linear regression line
- this is the first prinipal component
- then the distance of the points from the line is the component score (I don’t really understand this part, but I get how the line is simple way to explain the two dimensional data and explains most of the variation in the data.)

##### Example: Principle components with iris dataset

- center and scale - for each point, subtract the mean and divide by the sd
- the summary of the model shows you the proportion of variance explained by each principal component
- I think the rotation is the distance of the point from each principal component or something like that.
```


```{r}
set.seed(1)
xy <- data.frame(x = (x <- rnorm(50, 2, 1)),
                 y = x + rnorm(50, 1, 0.5))
pca <- prcomp(xy)
z <- cbind(x = c(-1, 1), y = c(0, 0))
zhat <- z %*% t(pca$rotation[, 1:2])
zhat <- scale(zhat, center = colMeans(xy), scale = FALSE)
par(mfrow = c(1, 3))
plot(xy, main = "Orignal data (2 dimensions)")
plot(xy, main = "Orignal data with PC1")
abline(lm(y ~ x, data = data.frame(zhat - 10)), lty = "dashed")
grid()
plot(pca$x, main = "Data in PCA space")
grid()
```


```{r}
pairs(iris[, -5], col = iris[, 5], pch = 19)

```


```{r}
%md
In R, we can use the `prcomp` function. 

Let's explore PCA on the `iris` data. While it contains only 4
variables, is already becomes difficult to visualise the 3 groups
along all these dimensions.
```


```{r}
irispca <- prcomp(iris[, -5])
summary(irispca)
```


```{r}
?prcomp

```


```{r}
#A summary of the `prcomp` output shows that along PC1 along, we are able to retain over 92% of the total variability in the data.

## boxplot(irispca$x[, 1] ~ iris[, 5], ylab = "PC1")
hist(irispca$x[iris$Species == "setosa", 1],
     xlim = range(irispca$x[, 1]), col = "#FF000030",
     xlab = "PC1", main = "PC1 variance explained 92%")
rug(irispca$x[iris$Species == "setosa", 1], col = "red")
hist(irispca$x[iris$Species == "versicolor", 1], add = TRUE, col = "#00FF0030")
rug(irispca$x[iris$Species == "versicolor", 1], col = "green")
hist(irispca$x[iris$Species == "virginica", 1],  add = TRUE, col = "#0000FF30")
rug(irispca$x[iris$Species == "virginica", 1], col = "blue")
```


```{r}
plot(irispca)
```


```{r}
%md
A biplot features all original points re-mapped (rotated) along the first two PCs as well as the original features as vectors along the same PCs. Feature vectors that are in the same direction in PC space are also correlated in the original data space.
```


```{r}
?biplot
```


```{r}
biplot(irispca)

```


```{r}
%md
One important piece of information when using PCA is the proportion of variance explained along the PCs, in particular when dealing with high dimensional data, as PC1 and PC2 (that are generally used for visualisation), might only account for an insufficient proportion of variance to be relevant on their own.

In the code chunk below, I extract the standard deviations from the PCA result to calculate the variances, then obtain the percentage of and cumulative variance along the PCs.
```


```{r}
var <- irispca$sdev^2
(pve <- var/sum(var))

#Proportion of Variance Explained (PVE)
```


```{r}
cumsum(pve)
```


```{r}
%md
Challenge

- Repeat the PCA analysis on the iris dataset above, reproducing the biplot and preparing a barplot of the percentage of variance explained by each PC.
- It is often useful to produce custom figures using the data coordinates in PCA space, which can be accessed as x in the prcomp object. Reproduce the PCA plots below, along PC1 and PC2 and PC3 and PC4 respectively.
```


```{r}
par(mfrow = c(1, 2))
plot(irispca$x[, 1:2], col = iris$Species)
plot(irispca$x[, 3:4], col = iris$Species)
```


```{r}
par(mfrow = c(1, 2))
plot(irispca$x[, c(1,3)], col = iris$Species)
plot(irispca$x[, 2:3], col = iris$Species)
```


```{r}
%md
#Data pre-processing
We haven’t looked at other prcomp parameters, other that the first one, x. There are two other ones that are or importance, in particular in the light of the section on pre-processing above, which are center and scale.. The former is set to TRUE by default, while the second one is set the FALSE.

Challenge

Repeat the analysis comparing the need for scaling on the mtcars dataset, but using PCA instead of hierarchical clustering. When comparing the two.
```


```{r}
par(mfrow = c(1, 2))
biplot(prcomp(mtcars, scale = FALSE), main = "No scaling")  ## 1
biplot(prcomp(mtcars, scale = TRUE), main = "With scaling") ## 2


#Without scaling, disp and hp are the features with the highest loadings along PC1 and 2 (all others are negligible), which are also those with the highest units of measurement. Scaling removes this effect.
```


```{r}
%md
# Final comments on PCA
Real datasets often come with missing values. In R, these should be encoded using NA. Unfortunately, PCA cannot deal with missing values, and observations containing NA values will be dropped automatically. This is a viable solution only when the proportion of missing values is low.

It is also possible to impute missing values. This is described in greater details in the Data pre-processing section in the supervised machine learning chapter.

Finally, we should be careful when using categorical data in any of the unsupervised methods described above. Categories are generally represented as factors, which are encoded as integer levels, and might give the impression that a distance between levels is a relevant measure (which it is not, unless the factors are ordered). In such situations, categorical data can be dropped, or it is possible to encode categories as binary dummy variables. For example, if we have 3 categories, say A, B and C, we would create two dummy variables to encode the categories as:
```


```{r}
dfr <- data.frame(x = c(1, 0, 0),
                  y = c(0, 1, 0))
rownames(dfr) <- LETTERS[1:3]
knitr::kable(dfr)
```


```{r}
%md
To perform dimension reduction techniques in R, generally, the data should be prepared as follows:

- Data are in tidy format per Wickham and others (2014);
- Any missing values in the data must be removed or imputed;
- Typically, the data must all be numeric values (e.g., one-hot, label, ordinal encoding categorical features);
- Numeric data should be standardized (e.g., centered and scaled) to make features comparable.
```

